# .choreo/source-config.yaml
version: "1.0"

endpoints:
  - name: rest-api-be2
    displayName: REST API
    port: 8000
    context: /
    type: REST
    networkVisibilities:
      - Project
      - Public
