# backend/.choreo/source-config.yaml
schemaVersion: "1.2"

endpoints:
  - name: rest-api-be2
    displayName: "REST API"
    type: REST
    networkVisibilities:
      - Public
      - Project
    service:
      port: 8000
      basePath: /
